<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <NoWarn>$(NoWarn);CA2007;CA1308;CA1062;CA1848</NoWarn>
        <UserSecretsId>7b8d7de1-4701-4e3e-af1d-3b3dd84c4afe</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Immediate.Apis" Version="6.4.0" />
        <PackageReference Include="Immediate.Handlers" Version="4.2.0" />

        <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
        <PackageReference Include="Google.Apis.Drive.v3" Version="1.76.0.4261" />

        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.17.6" />

        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ssera.Shared\Ssera.Shared.csproj" />
    </ItemGroup>
</Project>
